version: "3.8"

name: billing-service

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: billing-postgres
    hostname: ${POSTGRES_HOST}
    restart: on-failure
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - env/postgres

  nginx:
   image: nginx:${NGINX_VERSION}
   container_name: billing-nginx
   hostname: ${NGINX_HOST}
   restart: on-failure
   ports:
     - ${SERVER_PORT}:${SERVER_PORT}
   expose:
     - ${SERVER_PORT}
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
   env_file:
     - env/general

  backend:
    build: ../backend
    container_name: billing-backend
    hostname: ${BACKEND_HOST}
    restart: on-failure
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - env/general
      - env/backend
      - env/postgres
    depends_on:
      - postgres

  admin-panel:
    build: ../admin-panel
    container_name: billing-admin
    hostname: ${ADMIN_HOST}
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    expose:
      - ${ADMIN_PORT}
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    env_file:
      - env/general
      - env/admin
      - env/postgres
    depends_on:
      - postgres
      - backend

networks:
  default:
    name: billing-network

volumes:
  postgresql_data:
  static_volume:
