version: "3.8"

name: billing-service

services:
  postgres:
    image: postgres:13
    container_name: billing-postgres
    restart: on-failure
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  # nginx:
  #   image: nginx:${NGINX_VERSION}
  #   container_name: billing-nginx
  #   hostname: ${NGINX_HOST}
  #   restart: on-failure
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   expose:
  #     - ${SERVER_PORT}
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
  #   env_file:
  #     - env/general

networks:
  default:
    name: billing-network

volumes:
  postgresql_data:
