name: billing-test-service

services:
  tests:
    build: ../tests
    container_name: billing-test
    env_file:
      - env/general
      - env/tests
    depends_on:
      - postgres
      - backend


networks:
  default:
    name: billing-test-network

volumes:
  postgresql_test_data:
