services:
  postgres:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  backend:
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  admin-panel:
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}