"""empty message

Revision ID: f6ce348bc2a3
Revises:
Create Date: 2023-11-04 20:00:28.461717

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f6ce348bc2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS users;")
    op.create_table('permission',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='users'
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='users'
    )
    op.create_table('service',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('user',
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('time_zone', sa.String(length=100), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='users'
    )
    op.create_table('access_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('access_time', 'id'),
    sa.UniqueConstraint('id', 'access_time'),
    schema='users',
    postgresql_partition_by='RANGE (access_time)'
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['users.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['users.role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='users'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='users'
    )
    op.create_table('user_service',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('user_service_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['users.service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'service_id', 'user_service_id'),
    schema='users'
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS access_history_2023 PARTITION OF users.access_history FOR VALUES FROM ('01.01.2023') TO ('01.01.2024')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS access_history_2024 PARTITION OF users.access_history FOR VALUES FROM ('01.01.2024') TO ('01.01.2025')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS access_history_2025 PARTITION OF users.access_history FOR VALUES FROM ('01.01.2025') TO ('01.01.2026')"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TABLE IF EXISTS access_history_2023""")
    op.execute("""DROP TABLE IF EXISTS access_history_2024""")
    op.execute("""DROP TABLE IF EXISTS access_history_2025""")
    op.drop_table('user_service', schema='users')
    op.drop_table('user_role', schema='users')
    op.drop_table('role_permission', schema='users')
    op.drop_table('access_history', schema='users')
    op.drop_table('user', schema='users')
    op.drop_table('service', schema='users')
    op.drop_table('role', schema='users')
    op.drop_table('permission', schema='users')
    op.execute("DROP SCHEMA IF EXISTS users;")
    # ### end Alembic commands ###
