"""empty message

Revision ID: 0e82faaa4336
Revises: f6ce348bc2a3
Create Date: 2023-11-04 23:44:12.589513

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e82faaa4336'
down_revision = 'f6ce348bc2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('content_permission_rank', sa.SmallInteger(), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'content_permission_rank', schema='users')
    # ### end Alembic commands ###
